blank_issues_enabled: false
contact_links:
  - name: WoW Addon Development Discord
    url: https://discord.gg/addon-dev
    about: Get help from the community
  - name: Wowpedia API Reference
    url: https://warcraft.wiki.gg/wiki/World_of_Warcraft_API
    about: Official WoW API documentation
